### ISSUE TITLE
Test prisma with cockroachdb

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/appdev-issues#12]
There is a prisma issue (https://github.com/prisma/prisma/issues/1705) that shows a large amount of interest. 

Known issues:
- [x] Prisma is currently blocked on [not supporting user-defined schemas](https://github.com/cockroachdb/cockroach/issues/26443) but this may hide additional missing features. UPDATE: This PR worked around the issue: https://github.com/cockroachdb/cockroach/pull/42703
- [ ] `SELECT ... COLLATE "default"` https://github.com/cockroachdb/cockroach/issues/50734

**Comment by vy-ton** [comment]
Prisma [issue](https://github.com/prisma/prisma/issues/2523) to track support

**Comment by vy-ton** [comment]
Closing since this is now tracked on our roadmap and [this issue](https://github.com/cockroachdb/cockroach/issues/58615) tracks adding CI nightlies
