### ISSUE TITLE
Figure out pinning roachtests

### ISSUE THREAD

**Issue by apantel** [cockroachdb/appdev-issues#15]
Pin all ORM roachtests to a working version.

Ensure that newly available ORM versions are collected and surfaced somewhere that we will reliably see.

Ensure that it's easy to update the tested version when we want to

Maybe add pinned and unpinned roachtests, where the pinned ones are release blockers and the unpinned ones let us know when we can easily upgrade

**Comment by rafiss** [comment]
Let's use the versions on this docs page when pinning: https://www.cockroachlabs.com/docs/stable/third-party-database-tools.html

**Comment by rafiss** [comment]
PRs all look good to go:
https://github.com/cockroachdb/cockroach/pull/49595
https://github.com/cockroachdb/cockroach/pull/49839
https://github.com/cockroachdb/cockroach/pull/49994
