### ISSUE TITLE
sql: trigger ORM nightlies on unmerged pr 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/appdev-issues#16]
@knz has a pr for savepoints that he would like to be able to run against the ORM test suites. Is there a way for him to trigger this pr to run the ORM nightlies without merging the PR? this could help him speed up development in his comparison testing

@rafiss

**Comment by rafiss** [comment]
The roachtests can be run with a local build (running on a GCE cluster):

```
build/builder.sh mkrelease
make bin/roachprod
make bin/roachtest
roachtest run <ORM name>
```

**Comment by knz** [comment]
I am aware of local builds. 

1) That is specifically what I do not want (it takes forever) and that's why I wanted a CI target if any.

2) doesn't give me a command to 'run them all'

**Comment by rafiss** [comment]
I see -- I didn't understand these requirements.

This should be possible to do through TeamCity. I haven't done it myself, but I believe @ajwerner may have. I just tried a few things, and these instructions should work for what you want:

1. Go to the job in TeamCity: https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_Nightlies_WorkloadNightly
2. Click the three dots `...` next to `Run` near the top of the page.
3. In the modal that pops up, go to the `Changes` tab.
4. In the `Build branch` field, put the open PR number that includes your changes.
5. Click `Run build`.

**Comment by knz** [comment]
awesome! That's helpful. Thank you!
