### ISSUE TITLE
Design a basic connection pooling performance test

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/appdev-issues#37]
We should test how popular connection pooling libraries work with CockroachDB.

We want the test to measure performance (i.e., any additional overhead imposed by the connection pool) and to verify correctness.

**Comment by rafiss** [comment]
Vy had a meeting with the SE team. They said they needed this. When we have a v1 recommendation, let’s share with Lance, Glenn, and Alex.

**Comment by solongordon** [comment]
This is being addressed as a 20.2 work item.
