### ISSUE TITLE
Liquibase: Error out when runInTransaction=true is set

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/appdev-issues#44]
Follow up on https://github.com/cockroachdb/appdev-issues/issues/34

We should explicitly disable runInTransaction by erroring so it's clear to the user that it is not supported.

Right now transactional schema changes are not in a state where runInTransaction should be used and has some unexpected behaviour.

**Comment by rafiss** [comment]
@RichardJCai can you file an issue on the Liquibase repo with some background in it? It's probably better to track there

**Comment by rafiss** [comment]
Filed on liquibase
