### ISSUE TITLE
Run Spring petclinic example app with CockroachDB

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/appdev-issues#7]
https://github.com/spring-petclinic/spring-framework-petclinic

This project is a "canonical" Java app that uses Spring. It works with MySQL. Let's get it to work with CockroachDB too.

**Comment by apantel** [comment]
The `alter sequence` lines need to be removed from the cockroach version of initDB.sql. I also changed the port in petclinic_test_plan.jmx to not conflict.
